### ISSUE TITLE
native libs build does not work on smp targets  

### ISSUE THREAD

**Issue by sg2342** [jj1bdx/erlang-freebsd-port#4]
unfortunately #3  does not what one would assume:
1. native code for smp enabled systems is different from native code for systems without hipe
2. whether the native code in the .beam file compiled with +native is of the smp variant or not is determined by the availability of smp support in the VM used to compile the .beam.
3. the tooling variant used by the FreeBSD port somehow adds "-smp disable" to the ERLC flags

Because of 1. 2. and 3. the native libs produced by the port are always of the non-smp variant.

One can get native libs of the smp variant with 'FLAVOR=smp' added to CONFIGURE_ENV and MAKE_ENV. The build stops in lib/hipe/rtl: it uses beam (not beam.smp) for ERLC. copying beam.smp to beam solves this and let the build continue.

As far as i can tell the ./configure ... ; gmake ... variant of the otp build from  tarball is broken for smp with native libs.

It is possible to build native libs with smp using sources from git (tested with tag OTP-17.1.2):
```
./otp_build autoconf && 
FLAVOR=smp ./otp_build configure --enable-native-libs --enable-hipe --enable-smp-support \
                                 --enable-kernel-poll --without-odbc --enable-threads \
                                 --enable-sctp --with-ssl=/usr  && 
FLAVOR=smp ./otp_build smp
```

**Comment by jj1bdx** [comment]
No further update. Issue closed.
