### ISSUE TITLE
link to freshports (suggestion)

### ISSUE THREAD

**Issue by vitorsvieira** [jj1bdx/erlang-freebsd-port#6]
Hi, 

Nice work btw. Just my 2 cents. 

Would help the people that land at this repo to see link to this port at the readme. 

Link to port: https://www.freshports.org/lang/erlang/

**Comment by jj1bdx** [comment]
I'll put the link into README.md. Thanks for suggestion.

**Comment by jj1bdx** [comment]
Done.  See https://github.com/jj1bdx/erlang-freebsd-port/commit/9679b21c9cdb0557e5ccbc613a40b8b3765f973e#diff-04c6e90faac2675aa89e2176d2eec7d8
